### ISSUE TITLE
Upcoming linter changes

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-roodi#5]
We're in the process of replacing `linter` with a rewrite. Our central issue for tracking the plan is https://github.com/AtomLinter/linter-plus/issues/29. We're working hard to make this a smooth transition for you and for your users.

Please let us know here if you'd prefer to do the work yourself. If you have any questions or concerns please join us in our [room on gitter](https://gitter.im/AtomLinter/Linter).

**Comment by evjan** [comment]
I can do the work myself, but I'm not sure what this entails. Looking at the referenced issue I don't see what I'm meant to do. Could you please clarify?

**Comment by evjan** [comment]
Done in dab7219f19fcfcf1bf9ce4c449e24b166930b86a
